### ISSUE TITLE
Cannot find tab

### ISSUE THREAD

**Issue by PrashantZignuts** [SamuelScheit/puppeteer-stream#152]
when using latest version of puppeteer-stream(i.e 3.0.9) at that time getting error as 

Error: Cannot find tab
    at getStream (/Users/ztlab57/Desktop/puppeterRecording/node_modules/puppeteer-stream/dist/PuppeteerStream.js:171:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.recordMSTeams [as meetrecorder/recordmsteams] (/Users/ztlab57/Desktop/puppeterRecording/api/controllers/MeetRecorderController.js:226:30)

**Comment by PrashantZignuts** [comment]
yes i know it was added in 3.0.8 but i need to use multiple tab for single browser instance so it would be good if @SamuelScheit get some solution for this.

**Comment by PrashantZignuts** [comment]
Hello @SamuelScheit, 
tried 3.0.10 still getting the same issue
![image (5)](https://github.com/SamuelScheit/puppeteer-stream/assets/118741696/4bcd775e-ce06-4c24-bafb-bbc71e8df806)

**Comment by SamuelScheit** [comment]
fixed in version 3.0.12 4ff9b8f
let me know if the issue still occurs
