### ISSUE TITLE
Randomly get Error: Evaluation failed: ReferenceError: START_RECORDING is not defined

### ISSUE THREAD

**Issue by unicornsoftwareinc** [SamuelScheit/puppeteer-stream#74]
Hi there, I'm running this on an AWS instance and I'd say every 1 in 10 or 1 in 20 executions, I see the following error:

`Error: Evaluation failed: ReferenceError: START_RECORDING is not defined
    at __puppeteer_evaluation_script__:3:13
    at ExecutionContext._evaluateInternal (/home/webinarkit/code/webinarkit-social-streaming/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/webinarkit/code/webinarkit-social-streaming/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)`

Can't really seem to pinpoint what might be causing this. Any hints that might point me in the right direction?

Thanks!

**Comment by ductuannguyen1999** [comment]
Is there any update to this issue yet? I'm having the same error while trying to run in a Docker container.

**Comment by unicornsoftwareinc** [comment]
@ductuannguyen1999 I am still experiencing this issue. A workaround that I don't love is calling await page.waitForTimeout(5000);

Seems to work fairly consistently as long as the page loads fully. The downside of this is I lose 5 seconds or so of the recording.

**Comment by SamuelScheit** [comment]
I've rewritten the transmission method and it should be more performant and reliable, please try with the latest version
```
npm i puppeteer-stream@latest
```
