### ISSUE TITLE
When I use --use-fake-ui-for-media-stream the stream function gets some error

### ISSUE THREAD

**Issue by Harsh4999** [SamuelScheit/puppeteer-stream#98]
const browser = await launch({
        defaultViewport: null,
        executablePath: puppeteer.executablePath(),
        args: [ '--disable-setuid-sandbox', '--no-sandbox', '--window-size=1920,1080','--use-fake-ui-for-media-stream'],
        ignoreDefaultArgs: ['--mute-audio'],
    });
    
     const stream = await getStream(page, { audio: true, video: false }).catch(err => console.log(err));
     
     Error:
     
           throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
              ^

Error: Evaluation failed: undefined
    at ExecutionContext._ExecutionContext_evaluate (/Users/harsh/POCAudioBot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/harsh/POCAudioBot/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:140:16)

**Comment by Harsh4999** [comment]
found solution using browser.defaultContext

**Comment by bdegomme** [comment]
hey Harsh, same issue here, could you explain your solution in more detail?
